modLoader="javafml"
loaderVersion="[43,)"
license="MIT"

[[mods]]
modId="create_alchemical_substances"
version="1.0.0"
displayName="Create Alchemical Substances"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
credits="Me"
authors="TT_TCS"
description='''
Adds chemicals to the Create mod.
'''

[[dependencies.create_alchemical_substances]]

modId="forge"

mandatory=true

versionRange="[43,)"

ordering="NONE"

side="BOTH"

[[dependencies.create_alchemical_substances]]
modId="minecraft"
mandatory=true

versionRange="[1.19.2,1.20)"
ordering="NONE"
side="BOTH"

[[dependencies.create_alchemical_substances]]
modId="create"
mandatory=true
versionRange="[0.5.1.i,)"
ordering="NONE"
side="BOTH"